"""initial schema

Revision ID: 589bcf7427d2
Revises: 
Create Date: 2026-03-20 12:09:28.084116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589bcf7427d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_event',
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_date', 'audit_event', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_event', ['entity_type', 'entity_id'], unique=False)
    op.create_table('currency_rate',
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'observed_at', name='uq_currency_rate')
    )
    op.create_index('idx_currency_pair', 'currency_rate', ['from_currency', 'to_currency', 'observed_at'], unique=False)
    op.create_table('import_rule',
    sa.Column('buyer_country', sa.String(length=2), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=True),
    sa.Column('origin_country', sa.String(length=2), nullable=True),
    sa.Column('duty_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('de_minimis_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('de_minimis_currency', sa.String(length=3), nullable=True),
    sa.Column('customs_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_rule_lookup', 'import_rule', ['buyer_country', 'product_category'], unique=False)
    op.create_table('merchant',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_marketplace', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('affiliate_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_merchant_country'), 'merchant', ['country'], unique=False)
    op.create_index(op.f('ix_merchant_is_active'), 'merchant', ['is_active'], unique=False)
    op.create_table('product',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('product_line', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('discontinued', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_search_trgm', 'product', ['canonical_name'], unique=False, postgresql_using='gin', postgresql_ops={'canonical_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_product_brand'), 'product', ['brand'], unique=False)
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.create_table('merchant_domain',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('whois_created', sa.Date(), nullable=True),
    sa.Column('has_https', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('merchant_shipping_rule',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('destination_country', sa.String(length=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('free_above', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_days_min', sa.Integer(), nullable=True),
    sa.Column('estimated_days_max', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'destination_country', name='uq_merchant_shipping')
    )
    op.create_table('product_variant',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_key', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=600), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'variant_key', name='uq_variant_key')
    )
    op.create_index('idx_variant_display_trgm', 'product_variant', ['display_name'], unique=False, postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_product_variant_slug'), 'product_variant', ['slug'], unique=True)
    op.create_table('trust_score',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trust_score_latest', 'trust_score', ['merchant_id', 'computed_at'], unique=False)
    op.create_table('trust_signal',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('signal_name', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trust_signal_merchant', 'trust_signal', ['merchant_id'], unique=False)
    op.create_table('crawl_job',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=30), nullable=True),
    sa.Column('recurrence_hours', sa.Integer(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_next_run', 'crawl_job', ['next_run'], unique=False, postgresql_where="status != 'blocked'")
    op.create_index('idx_crawl_pending', 'crawl_job', ['status'], unique=False, postgresql_where="status IN ('pending', 'running')")
    op.create_table('offer',
    sa.Column('product_variant_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('raw_title', sa.Text(), nullable=False),
    sa.Column('extracted_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('identifiers_found', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_currency', sa.String(length=3), nullable=True),
    sa.Column('shipping_source', sa.String(length=20), nullable=False),
    sa.Column('delivery_days_min', sa.Integer(), nullable=True),
    sa.Column('delivery_days_max', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('match_method', sa.String(length=30), nullable=True),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mismatch_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('last_price_change', sa.DateTime(), nullable=True),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_offer_review', 'offer', ['review_status'], unique=False, postgresql_where="review_status = 'pending'")
    op.create_index('idx_offer_variant_active', 'offer', ['product_variant_id'], unique=False, postgresql_where='is_active = true')
    op.create_table('price_alert',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buyer_country', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_notified', sa.DateTime(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_variant_active', 'price_alert', ['product_variant_id'], unique=False, postgresql_where='is_active = true')
    op.create_index(op.f('ix_price_alert_email'), 'price_alert', ['email'], unique=False)
    op.create_table('product_identifier',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_type', 'value', name='uq_identifier')
    )
    op.create_index('idx_identifier_lookup', 'product_identifier', ['identifier_type', 'value'], unique=False)
    op.create_table('product_search_alias',
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alias_trgm', 'product_search_alias', ['alias'], unique=False, postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.create_table('search_query',
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('parsed_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_product_id', sa.UUID(), nullable=True),
    sa.Column('matched_variant_id', sa.UUID(), nullable=True),
    sa.Column('disambiguation_shown', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('buyer_country', sa.String(length=2), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['matched_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['matched_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_date', 'search_query', ['created_at'], unique=False)
    op.create_index('idx_search_product', 'search_query', ['matched_product_id'], unique=False)
    op.create_table('extraction_result',
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_title', sa.Text(), nullable=True),
    sa.Column('extracted_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extracted_currency', sa.String(length=3), nullable=True),
    sa.Column('extracted_ean', sa.String(length=20), nullable=True),
    sa.Column('extracted_availability', sa.String(length=20), nullable=True),
    sa.Column('parsing_method', sa.String(length=20), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('llm_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_cost_usd', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('extraction_quality', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_crawl', 'extraction_result', ['crawl_job_id'], unique=False)
    op.create_table('offer_price_snapshot',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_snapshot_offer_time', 'offer_price_snapshot', ['offer_id', 'observed_at'], unique=False)
    op.create_table('search_click',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_affiliate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['search_query.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_click_offer', 'search_click', ['offer_id'], unique=False)
    op.create_index('idx_click_query', 'search_click', ['query_id'], unique=False)
    op.create_table('total_cost_estimate',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('buyer_country', sa.String(length=2), nullable=False),
    sa.Column('base_price_local', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('exchange_spread', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('import_duty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('import_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customs_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_cost_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'buyer_country', name='uq_total_cost_offer_country')
    )
    op.create_index('idx_total_cost_offer', 'total_cost_estimate', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_total_cost_offer', table_name='total_cost_estimate')
    op.drop_table('total_cost_estimate')
    op.drop_index('idx_click_query', table_name='search_click')
    op.drop_index('idx_click_offer', table_name='search_click')
    op.drop_table('search_click')
    op.drop_index('idx_price_snapshot_offer_time', table_name='offer_price_snapshot')
    op.drop_table('offer_price_snapshot')
    op.drop_index('idx_extraction_crawl', table_name='extraction_result')
    op.drop_table('extraction_result')
    op.drop_index('idx_search_product', table_name='search_query')
    op.drop_index('idx_search_date', table_name='search_query')
    op.drop_table('search_query')
    op.drop_index('idx_alias_trgm', table_name='product_search_alias', postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    op.drop_table('product_search_alias')
    op.drop_index('idx_identifier_lookup', table_name='product_identifier')
    op.drop_table('product_identifier')
    op.drop_index(op.f('ix_price_alert_email'), table_name='price_alert')
    op.drop_index('idx_alert_variant_active', table_name='price_alert', postgresql_where='is_active = true')
    op.drop_table('price_alert')
    op.drop_index('idx_offer_variant_active', table_name='offer', postgresql_where='is_active = true')
    op.drop_index('idx_offer_review', table_name='offer', postgresql_where="review_status = 'pending'")
    op.drop_table('offer')
    op.drop_index('idx_crawl_pending', table_name='crawl_job', postgresql_where="status IN ('pending', 'running')")
    op.drop_index('idx_crawl_next_run', table_name='crawl_job', postgresql_where="status != 'blocked'")
    op.drop_table('crawl_job')
    op.drop_index('idx_trust_signal_merchant', table_name='trust_signal')
    op.drop_table('trust_signal')
    op.drop_index('idx_trust_score_latest', table_name='trust_score')
    op.drop_table('trust_score')
    op.drop_index(op.f('ix_product_variant_slug'), table_name='product_variant')
    op.drop_index('idx_variant_display_trgm', table_name='product_variant', postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.drop_table('product_variant')
    op.drop_table('merchant_shipping_rule')
    op.drop_table('merchant_domain')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    op.drop_index('idx_product_search_trgm', table_name='product', postgresql_using='gin', postgresql_ops={'canonical_name': 'gin_trgm_ops'})
    op.drop_table('product')
    op.drop_index(op.f('ix_merchant_is_active'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_country'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index('idx_import_rule_lookup', table_name='import_rule')
    op.drop_table('import_rule')
    op.drop_index('idx_currency_pair', table_name='currency_rate')
    op.drop_table('currency_rate')
    op.drop_index('idx_audit_entity', table_name='audit_event')
    op.drop_index('idx_audit_date', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
